# Generated by Django 5.1.7 on 2025-04-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
